"""
state.py

Defines the shared state used throughout the LangGraph workflow.

The state stores:
- User input
- LLM responses
- Tool outputs
- Ticket information
- Human review status
- Conversation messages
"""

from __future__ import annotations

from typing import Annotated, Optional

from langgraph.graph.message import add_messages
from typing_extensions import TypedDict

from langchain_core.messages import BaseMessage


class SupportAgentState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    """

    # Conversation history (required for ToolNode + Memory)
    messages: Annotated[list[BaseMessage], add_messages]

    # User issue
    user_issue: str

    # Classification
    category: Optional[str]

    # Priority
    priority: Optional[str]

    # Knowledge Base Result
    kb_result: Optional[str]

    # System Status
    system_status: Optional[str]

    # Draft generated by Gemini
    draft_response: Optional[str]

    # Final approved response
    final_response: Optional[str]

    # Ticket information
    ticket_id: Optional[str]

    # Human approval
    needs_human_review: bool

    # Human decision
    approval_status: Optional[str]