"""
models.py

Pydantic models used throughout the
SmartKart AI Customer Support project.
"""

from pydantic import BaseModel, Field
from typing import Optional


# --------------------------------------------------
# Customer Query
# --------------------------------------------------

class CustomerQuery(BaseModel):
    """
    Represents a customer query.
    """

    question: str = Field(
        ...,
        description="Customer question"
    )


# --------------------------------------------------
# Tool Result
# --------------------------------------------------

class ToolResult(BaseModel):
    """
    Standard response returned by business tools.
    """

    tool_name: str

    success: bool = True

    result: str


# --------------------------------------------------
# Customer Support Response
# --------------------------------------------------

class CustomerSupportResponse(BaseModel):
    """
    Final response generated by the AI Assistant.
    """

    answer: str

    tool_used: Optional[str] = None

    requires_human_agent: bool = False